version: '3.8'

services:
  db:
    image: postgres:13
    container_name: sso_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: sso_backend
    restart: always
    depends_on:
      - db
    ports:
      - "4000:4000"
    volumes:
      - ./backend/logs:/usr/src/app/logs # Adicionado
    environment:
      - NODE_ENV=production # Importante para ativar o logging em ficheiro
      - DATABASE_URL=postgres://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - PORT=4000
      - FRONTEND_URL=${FRONTEND_URL}
      - JWT_SECRET=${JWT_SECRET}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
      - MAIL_USER=${MAIL_USER}
      - MAIL_PASS=${MAIL_PASS}
      - MAIL_FROM=${MAIL_FROM}
      - LDAP_URL=${LDAP_URL}
      - LDAP_BIND_DN=${LDAP_BIND_DN}
      - LDAP_BIND_PASSWORD=${LDAP_BIND_PASSWORD}
      - LDAP_SEARCH_BASE=${LDAP_SEARCH_BASE}
    command: npm run start

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: sso_frontend
    restart: always
    ports:
      - "5173:80"

volumes:
  postgres_data: